### ISSUE TITLE
Quantitative comparison between the hot diffusion and the cold diffusion

### ISSUE THREAD

**Issue by AndysonYs** [arpitbansal297/Cold-Diffusion-Models#2]
This is amazing work. Thanks for your contribution.

In the Sec.3 of your paper, you present the quantitative results of using the deblurring model, the inpainting model, the SR model, and the snowfication model. I am wondering what is the hot diffusion(denoising model)'s quantitative result under the same setting as your cold diffusion experiments. Would you like to show it?

**Comment by arpitbansal297** [comment]
We do show the quantitative results for noise in section 5.
