### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by zcc31415926** [arpitbansal297/Cold-Diffusion-Models#3]
Thanks for the creative work of Cold Diffusion. The results are very impressive.

I want to use Cold Diffusion as backbone for downstream tasks. Are there any pretrained models or checkpoint files you would like to share?

**Comment by arpitbansal297** [comment]
Thanks, we have added pre-trained models in google drive. We have added a link to our Readme file.

**Comment by zcc31415926** [comment]
Thank you very much!
