### ISSUE TITLE
Please don't link directly to Arxiv pdfs

### ISSUE THREAD

**Issue by black-puppydog** [arpitbansal297/Cold-Diffusion-Models#4]
![image](https://user-images.githubusercontent.com/189241/188191219-537fe0da-4eef-4b87-91ba-4b3a20b8982d.png)

As a general rule, please link to the abstract, not the pdf file. It helps with "save to zotero" and such, but also reduces load on the arxiv servers from people who just casually click the link to see what's behind it.

Nice work though :)

**Comment by arpitbansal297** [comment]
Solved
