### ISSUE TITLE
AttributeError: 'GaussianDiffusion' object has no attribute 'module'

### ISSUE THREAD

**Issue by Amarkr1** [arpitbansal297/Cold-Diffusion-Models#8]
https://github.com/arpitbansal297/Cold-Diffusion-Models/blob/f8b1379151ff0cccba49112cf61d439bd4dd4ad9/deblurring-diffusion-pytorch/deblurring_diffusion_pytorch/deblurring_diffusion_pytorch.py#L1241

Modified this to:
`X_0s, X_ts = self.ema_model.all_sample(batch_size=batches, img=og_img, times=s_times) # change for DP`

seems to solve the error.

**Comment by arpitbansal297** [comment]
Yes, .module is there because of data parallel.
